name: appknox-agent
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - google-genai
      - langfuse
      - deepeval
      - rich
      - python-dotenv
      - tiktoken
      - pytest
